name: arctern-demo
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Merge:
    if: github.event.pull_request.merged == true
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Time Zone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v1.1.0
        with:
          version: '12.x'
   
      - name: Check out Git repository
        uses: actions/checkout@v2
  
      - name: Docker login
        run: echo '${{ secrets.DOCKER_PWD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
      - name: Docker Build
        run: docker build -t zilliz/infini-webclient:arctern-demo .

      - name: Docker Push version
        run: docker push zilliz/infini-webclient:arctern-demo
